### ISSUE TITLE
Typo (should be "maximum", not "maximim") :))

### ISSUE THREAD

**Issue by ginsterbusch** [azurecurve/azrcrv-nearby#1]
https://github.com/azurecurve/azrcrv-nearby/blob/1bafcebcc2922999ed9438c64fcdcdde4b25cddc/azrcrv-nearby.php#L127

**Comment by azurecurve** [comment]
So, by fixing that do I make this my first 2.0 plugin as it is technically a breaking fix?

**Comment by azurecurve** [comment]
Fixed issue and released v2.0.0
